### ISSUE TITLE
建议仅保留 N 天内的日志

### ISSUE THREAD

**Issue by fufuok** [gxlog/gxlog#2]
很棒很实用的日志，用在了好些项目上了。
无依赖；JOSN 也很棒，方便入 ES。Coloring，WithMark，WithCountLimit，Timingf 都很实用。
只是 Aux 生成的 JSON 在子结构中，不扁平，问题不大。

按天建目录并将日志文件按大小自动切割，我觉得是最酷的功能。
**唯一问题是觉得日志目录越建越多，没有滚动清理或压缩打包，比如常见的仅保留最近 n 天日志的功能。**

![image](https://user-images.githubusercontent.com/4979407/113163404-ba08d480-9272-11eb-9a62-c838e699ad96.png)

**Comment by gratonos** [comment]
感谢采用了本项目，以及给出建议。

`gxlog`的配置项做得很丰富和灵活，例如可以不重启进程随时通过方法调用修改产生的日志的目录格式和文件格式，所以，如果通过当前进程的当前配置来清理历史日志，可能出现误清理或者清理失败的问题。目前还没有比较简单优雅的直接清理或压缩的思路，在实际使用的过程中，或许可以考虑通过`Linux`的`crontab`命令来做定时清理或压缩。

**Comment by fufuok** [comment]
OK, 3ks.
